import Link from 'next/link';

const guideData: Record<string,{category:string,title:string,intro:string,sections:{title:string,text:string}[],product?:{name:string,image:string,link:string}}> = {
  'electrical-engineering-toolkit': { category:'Electrical Engineering', title:'The Electrical Engineering Student Toolkit', intro:'A practical starting point for building an engineering toolkit without buying everything at once.', sections:[{title:'Start with the basics',text:'A digital multimeter is one of the most useful first purchases. It lets you measure voltage, current and resistance and supports many introductory lab and project tasks.'},{title:'What to add next',text:'Consider test leads and clips, a basic soldering setup, wire tools, a small screwdriver set and safe storage. Buy based on the projects you actually do.'},{title:'What to look for',text:'For a multimeter, pay attention to measurement functions, safety category, input protection, display readability and whether auto-ranging is useful for your work.'}], product:{name:'Klein Tools MM450 Auto-Ranging Multimeter',image:'https://data.kleintools.com/sites/all/product_assets/hires/klein/mm450_photo_c.jpg',link:'https://amzn.to/4zewrjd'} },
  'how-to-choose-a-multimeter': { category:'Electrical Engineering', title:'How to Choose Your First Multimeter', intro:'Understand the important specifications before spending money on a meter.', sections:[{title:'Auto-ranging vs manual-ranging',text:'Auto-ranging meters select an appropriate measurement range for you. Manual-ranging meters require you to select the range. For students, auto-ranging can make everyday measurements simpler.'},{title:'TRMS matters',text:'True RMS measurement can provide more meaningful AC measurements for non-sinusoidal waveforms than basic average-responding meters.'},{title:'Safety rating',text:'Look at the meter’s measurement category and voltage rating. Never choose a meter solely because it has a higher-looking number; use equipment appropriate for the circuit being tested.'}], product:{name:'Klein Tools MM450 Auto-Ranging Multimeter',image:'https://data.kleintools.com/sites/all/product_assets/hires/klein/mm450_photo_c.jpg',link:'https://amzn.to/4zewrjd'} },
  'student-essentials': { category:'Student Life', title:'The Student Essentials Buying Guide', intro:'A simple framework for deciding which products are worth adding to a college setup.', sections:[{title:'Buy for repeated use',text:'Prioritize products you will use every week: study accessories, charging gear, storage, basic tools and items that solve a recurring problem.'},{title:'Avoid unnecessary upgrades',text:'A higher price does not automatically mean a better fit. Compare the features you actually need rather than buying based on popularity alone.'},{title:'Build gradually',text:'Start with a small core kit and expand when a class, project or daily routine creates a genuine need.'}] }
};

export default async function GuidePage({params}:{params:Promise<{slug:string}>}) { const {slug}=await params; const guide=guideData[slug]; if(!guide) return <main><div className="container"><h1>Guide not found</h1><Link href="/guides">← Back to guides</Link></div></main>; return <main><nav className="nav container"><Link className="brand" href="/"><span className="brand-mark">C</span> CampusKit<span className="brand-light">Guide</span></Link><div className="nav-links"><Link href="/">Home</Link><Link href="/guides">Guides</Link></div></nav><div className="container"><Link className="back-link" href="/guides">← All guides</Link><header className="guide-detail-hero"><div className="eyebrow">{guide.category}</div><h1>{guide.title}</h1><p>{guide.intro}</p></header><article className="guide-detail"><div>{guide.sections.map((section,i)=><section className="detail-section" key={section.title}><span className="detail-number">0{i+1}</span><div><h2>{section.title}</h2><p>{section.text}</p></div></section>)}</div>{guide.product&&<aside className="guide-product"><div className="guide-product-image"><img src={guide.product.image} alt={guide.product.name}/></div><span className="guide-category">Recommended pick</span><h2>{guide.product.name}</h2><p>A practical option to consider after understanding the features above.</p><a className="primary-button" href={guide.product.link} target="_blank" rel="nofollow sponsored noopener">View on Amazon ↗</a></aside>}</article></div></main>; }
