const guides = [
  { title: 'Electrical Engineering Student Toolkit', category: 'Electrical Engineering', intro: 'A practical starting point for building an engineering toolkit without buying everything at once.', sections: [['Start with the basics','A digital multimeter is one of the most useful first purchases. It lets you measure voltage, current and resistance and supports many introductory lab and project tasks.'],['What to add next','Consider test leads and clips, a basic soldering setup, wire tools, a small screwdriver set and safe storage. Buy based on the projects you actually do.'],['What to look for','For a multimeter, pay attention to measurement functions, safety category, input protection, display readability and whether auto-ranging is useful for your work.']] },
  { title: 'How to Choose a Multimeter', category: 'Buying Guide', intro: 'Understand the important specifications before spending money on a meter.', sections: [['Auto-ranging vs manual-ranging','Auto-ranging meters select an appropriate measurement range for you. Manual-ranging meters require you to select the range. For students, auto-ranging can make everyday measurements simpler.'],['TRMS matters','True RMS measurement can provide more meaningful AC measurements for non-sinusoidal waveforms than basic average-responding meters.'],['Safety rating','Look at the meter’s measurement category and voltage rating. Never choose a meter solely because it has a higher-looking number; use equipment appropriate for the circuit being tested.']] },
  { title: 'Student Essentials Buying Guide', category: 'Student Essentials', intro: 'A simple framework for deciding which products are worth adding to a college setup.', sections: [['Buy for repeated use','Prioritize products you will use every week: study accessories, charging gear, storage, basic tools and items that solve a recurring problem.'],['Avoid unnecessary upgrades','A higher price does not automatically mean a better fit. Compare the features you actually need rather than buying based on popularity alone.'],['Build gradually','Start with a small core kit and expand when a class, project or daily routine creates a genuine need.']] },
];

export default function GuidesPage() {
  return <main><div className="container guides-page"><a className="back-link" href="/">← CampusKit Guide</a><header className="guide-hero"><div className="eyebrow">CampusKit Guides</div><h1>Know what you're buying.</h1><p>Practical, student-focused guides that explain what matters before you click “Buy.”</p></header><div className="guide-list">{guides.map((guide, i) => <article className="guide-card" key={guide.title}><div className="guide-index">0{i + 1}</div><div><span className="guide-category">{guide.category}</span><h2>{guide.title}</h2><p className="guide-intro">{guide.intro}</p>{guide.sections.map(([heading,text]) => <div className="guide-section" key={heading}><h3>{heading}</h3><p>{text}</p></div>)}<a className="guide-link" href="#top">Back to top ↑</a></div></article>)}</div></div></main>;
}
